<?php
namespace App;

class Application_Model_Constants
{
    	const GATEKEEPER_STATUS_VALID = 1 ;
    	const GATEKEEPER_STATUS_CHANGEPASSWORD = 2 ;
    	const GATEKEEPER_STATUS_CHANGEPASSWORDINVALIDCREDS = 3 ;
    	const GATEKEEPER_STATUS_INVALIDIP = 4 ;
    	const GATEKEEPER_STATUS_INVALIDCREDS = 5 ;
    	const GATEKEEPER_STATUS_INVALID_SESSION = 6;
    	const GATEKEEPER_STATUS_LOCKED = 7 ;
    	const GATEKEEPER_STATUS_CHANGEPASSWORDSTRENGTH = 8;
    	const GATEKEEPER_STATUS_CHANGEPASSWORDRECENT = 9;
    	const GATEKEEPER_STATUS_CODE_SENT = 10;
    	const GATEKEEPER_STATUS_INVALID_CODE = 11;
    	const GATEKEEPER_STATUS_SHORT_PASSWORD = 16;
    	const GATEKEEPER_STATUS_NOALPHA_PASSWORD = 17;
    	const GATEKEEPER_STATUS_NODIGIT_PASSWORD = 18;
    	const GATEKEEPER_STATUS_NOSPECIAL_PASSWORD = 19;
    	const GATEKEEPER_STATUS_SHORT_NOALPHA_PASSWORD = 20;
    	const GATEKEEPER_STATUS_SHORT_NODIGIT_PASSWORD = 21;
    	const GATEKEEPER_STATUS_SHORT_NOSPECIAL_PASSWORD = 22;
    	const GATEKEEPER_STATUS_NOALPHA_NODIGIT_PASSWORD = 23;
    	const GATEKEEPER_STATUS_NOALPHA_NOSPECIAL_PASSWORD = 24;
    	const GATEKEEPER_STATUS_NODIGIT_NOSPECIAL_PASSWORD = 25;
    	const GATEKEEPER_STATUS_SHORT_NOALPHA_NODIGIT_PASSWORD = 26;
    	const GATEKEEPER_STATUS_SHORT_NOALPHA_NOSPECIAL_PASSWORD = 27;
    	const GATEKEEPER_STATUS_SHORT_NODIGIT_NOSPECIAL_PASSWORD = 28;
    	const GATEKEEPER_STATUS_NOALPHA_NODIGIT_NOSEPCIAL_PASSWORD = 29;
    	const GATEKEEPER_STATUS_SHORT_NOALPHA_NODIGIT_NOSEPCIAL_PASSWORD = 30;
    	const GATEKEEPER_STATUS_INVALID_PERMISSIONS = 31;
    	const GATEKEEPER_VALID_SESSION = 36;
    	const GATEKEEPER_STATUS_GTA_NOT_REGISTERED = 47;
    	const GATEKEEPER_STATUS_GTA_ENABLED = 48;
    	const GATEKEEPER_STATUS_GTA_INVALID_CODE = 49;

    	const ADMIN = "ADMIN";
    	const USER = "USER";

        const TABLEMAINTENANCE_PERMISSION = "4639521";
        const REPORTSERVER_PERMISSION = "4639521";
        const ISTSCRUBBER_PERMISSION = "5";
        const IZOPS_PERMISSION = "4640021";
        const ANOMALY_PERMISSION = "4724231";
        const BUSINESSREPORTING_PERMISSION                  = "82441";
        const BUSINESSREPORTING_REPORTSERVER_ACCESS         = "4639521";
        const BUSINESSREPORTING_ADVANCED_ACCESS             = "4639721";
        const BUSINESSREPORTING_GROUPSERVER_ACCESS          = "4639621";
        const BUSINESSREPORTING_TSOPSTATUS_ACCESS           = "4639821";
        const BUSINESSREPORTING_EMPLOYEEMANAGEMENT_ACCESS   = "4639921";
        const BUSINESSREPORTING_TERRITORYMANAGEMENT_ACCESS  = "4640021";
        const BUSINESSREPORTING_ANOAMLYSETUP_ACCESS         = "4724231";
        const BUSINESSREPORTING_ANOMALYEXCEPTION_ACCESS     = "4724531";
        const BUSINESSREPORTING_REPORTMANAGEMENT_EDIT       = "4640221";
        const BUSINESSREPORTING_GROUPMANAGEMENT_EDIT        = "4640421";
        const BUSINESSREPORTING_ADVANCED_EDIT               = "4640521";
        const BUSINESSREPORTING_TSOPSTATUS_VIEW             = "4640621";
        const BUSINESSREPORTING_EMPLOYEEMANAGEMENT_EDIT     = "4640821";
        const BUSINESSREPORTING_TERRITORYMANAGEMENT_EDIT    = "4641121";
        const BUSINESSREPORTING_TERRITORYMANAGEMENT_EXPORT  = "4641221";
        const BUSINESSREPORTING_REPORTMANAGEMENT_VIEW       = "4640121";
        const BUSINESSREPORTING_GROUPMANAGEMENT_VIEW        = "4640321";
        const BUSINESSREPORTING_EMPLOYEEMANAGEMENT_VIEW     = "4640721";
        const BUSINESSREPORTING_TERRITORYMANAGEMENT_VIEW    = "4641021";
        const BUSINESSREPORTING_IPTRACKING_EDIT             = "4724431";
        const BUSINESSREPORTING_IPTRACKING_ACCESS           = "4724431";

        const BUSINESSREPORTING_ANOAMLYSETUP_EDIT           = "4724431";

        const BUSINESSREPORTING_ANOAMLYSETUP_SQLEDIT        = "4724431";

        const BUSINESSREPORTING_ANOMALYEXCEPTION_EDIT       = "4724731";

        const BUSINESSREPORTING_ANOAMLYSETUP_VIEW           = "4724331";

        const BUSINESSREPORTING_ANOMALYEXCEPTION_VIEW       = "4724631";

        const BUSINESSREPORTING_TRANSACTIONHISTORY_ACCESS   = "4878541";
        const BUSINESSREPORTING_TRANSACTIONHISTORY_EDIT     = "4878641";
        const BUSINESSREPORTING_ANOMALYREPORT_ACCESS        = "4878541";
        const BUSINESSREPORTING_ANOMALYREPORT_EDIT          = "4878641";
        const BUSINESSREPORTING_LEDGERREPORT_ACCESS         = "4878541";
        const BUSINESSREPORTING_LEDGERREPORT_EDIT           = "4878541";
        const BUSINESSREPORTING_LEDGERREPORTAPPROVAL_ACCESS = "4878541";
        const BUSINESSREPORTING_LEDGERREPORTAPPROVAL_VIEW   = "4878541";
        const BUSINESSREPORTING_LEDGERREPORTAPPROVAL_EDIT   = "4878541";

}


